- hosts: webserver
  vars_files:
    - vars.yaml
  tasks:
    - name: install httpd package
      package:
        name: "{{ package_name }}"
        state: present

    - name: start the service
      service:
        name: "{{ package_name }}"
        state: started
        enabled: yes

    - name: copy the index file
      copy:
        dest: "{{ dest }}"
        src: "{{ src }}"

